version: 2
jobs:
    build:
        docker:
            - image: golang:1.17.5-bullseye
        steps:
            - checkout
            - run:
                name: Install packages
                command: apt-get update && apt-get install -y make git

            - run:
                name: Build binary
                command: make build

            - store_artifacts:
                path: ./terraform-provider-algolia_v0.4

workflows:
    version: 2
    build:
        jobs:
            - build
