version: 2
jobs:
    build-linux-amd64:
        docker:
            - image: golang:1.17.5-bullseye
        steps:
            - checkout
            - run:
                name: Install packages
                command: apt-get update && apt-get install -y make git

            - run:
                name: Build binary
                command: GOOS=linux GOARCH=amd64 make build

            - store_artifacts:
                path: ./terraform-provider-algolia_v0.4

    build-macos-amd64:
        docker:
            - image: golang:1.17.5-bullseye
        steps:
            - checkout
            - run:
                name: Install packages
                command: apt-get update && apt-get install -y make git

            - run:
                name: Build binary
                command: GOOS=darwin GOARCH=amd64 make build

            - store_artifacts:
                path: ./terraform-provider-algolia_v0.4

    build-macos-arm64:
        docker:
            - image: golang:1.17.5-bullseye
        steps:
            - checkout
            - run:
                name: Install packages
                command: apt-get update && apt-get install -y make git

            - run:
                name: Build binary
                command: GOOS=darwin GOARCH=arm64 make build

            - store_artifacts:
                path: ./terraform-provider-algolia_v0.4

workflows:
    version: 2
    build:
        jobs:
            - build-linux-amd64
            - build-macos-amd64
            - build-macos-arm64
